### ISSUE TITLE
Typo in devlog.md

### ISSUE THREAD

**Issue by toddabrams** [mmazzarolo/chrome-another-tab#8]
`cd chrome-anoter-tab && yarn add @types/chrome`

should be another instead of anoter

`cd chrome-another-tab && yarn add @types/chrome`

**Comment by toddabrams** [comment]
`Initially I thought about just using the `Context` API, maybe in conjuntion`
to
`Initially I thought about just using the `Context` API, maybe in conjunction`

**Comment by mmazzarolo** [comment]
Updated, thank you @toddabrams !
